name: Integration

on:
  pull_request:
    branches: [main]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Poetry ğŸµ
        run: pipx install poetry

      - name: Setup Python ğŸ
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Setup Scripts ğŸ§©
        run: |
          poetry install
          poetry run inv env.switch ci
          poetry run inv tool.install ci-int --yes

      - name: Lint ğŸª¶
        run: poetry run inv lint

      - name: Test ğŸ§ª
        run: poetry run inv test
