name: Publication

on:
  push:
    branches: [main]

jobs:
  publication:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git âœ¨
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Setup Poetry ğŸµ
        run: pipx install poetry

      - name: Setup Python ğŸ
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Setup Scripts ğŸ§©
        run: |
          poetry install
          inv env.switch ci
          inv tool.install ci-dep --yes

      - name: Build ğŸ—ï¸
        run: inv build

      - name: Publish ğŸš€
        run: inv publish
